# Generated by Django 4.1.5 on 2023-01-18 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=228)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Todo"),
                            (1, "In Process"),
                            (2, "Done"),
                            (3, "Cancelled"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (0, "lowes"),
                            (1, "low"),
                            (2, "Middle"),
                            (3, "High"),
                            (4, "Highest"),
                        ],
                        default=2,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
